# Generated by Django 2.1.3 on 2018-11-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='picture',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='people',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique_for_date='publish'),
        ),
    ]
